app:
  api-errors:
    baseUrl: http://localhost:8080

spring:
  mvc:
    problemdetails:
      enabled: true
  messages:
    basename: "messages,config.i18n.messages"
    fallback-to-system-locale: false

springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /openapi.json

logging:
  level:
    root: ERROR
    dev.martins.marcio.studies.springbooti18n: INFO